services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack/data
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - "./localstack/init-dynamodb.sh:/docker-entrypoint-initaws.d/init-dynamodb.sh"
      - localstack_data:/var/lib/localstack
    entrypoint: [ "/bin/bash", "-c", "docker-entrypoint.sh & /docker-entrypoint-initaws.d/init-dynamodb.sh" ]

volumes:
  localstack_data: